### ISSUE TITLE
Error code 200, response -> {} 

### ISSUE THREAD

**Issue by ermaxinc** [st1vms/unofficial-claude2-api#12]
## Sometimes I get an error
```
Error code 200, response -> {} 
```

## My code:
```
if file is not None and os.path.exists(file):
    res: SendMessageResponse = client.send_message(
        chat_id=chat_id, prompt=text, attachment_paths=[file]
    )
else:
    res: SendMessageResponse = client.send_message(
        chat_id=chat_id, prompt=text
    )

if res.answer:
    result_answer = res.answer
else:
    self.__msg.error(f'Error code {res.status_code}, response -> {res.error_response} // MSG:{msg_num}', than_exit=False)
    self.__msg.error(f'{res}', than_exit=True)
```

## res is:
```
SendMessageResponse(answer='', status_code=200, error_response={}) 
```

## PS. But if i go to the Web, there's an answer in chat.

**Comment by st1vms** [comment]
Hi @ermaxinc, I have to know if this bug occurs multiple times in a row, or it's just some random error you encountered... also can I have a clue about the file content you're sending as attachment?

Since the `status_code` returned is 200, I'm guessing there is probably something wrong either in the `ClaudeAPIClient.__decode_response()` method (see [this line](https://github.com/st1vms/unofficial-claude2-api/blob/291702889e52e2d4fd56e9a889fc7f9752b70bc4/claude2_api/client.py#L156) ) or in the way the response is parsed as text ( [here](https://github.com/st1vms/unofficial-claude2-api/blob/291702889e52e2d4fd56e9a889fc7f9752b70bc4/claude2_api/client.py#L539) )

I may need to gather more info about this error before pushing a fix.

**Comment by st1vms** [comment]
More specifically I have to look for unproper decoding of responses ( if the compression took place ).

Also there should probably be a better way of parsing the response into the `answer` string object.

**Comment by st1vms** [comment]
@ermaxinc Thanks a lot for your feedback. Based off the `response.content` you provided, it seems that a new exception wrapping this error is what we need...

But also the `error_response` basically doesn't give any actual clue about any potential errors, the reason is because of a stinky json parsing strategy...so I think it's best off to let there be a property such as `raw_answer`, or smth like that, holding the `response.content` itself.

I'll be making a PR to test these things out whenever possible, meanwhile if you'd like to push your help, feel free to do the same. 

Thanks again :)

**Comment by st1vms** [comment]
@ermaxinc Let's move the discussion here... #13

 Waiting for your confirmation in order to push the new changes into the 0.2.7 release : )
